"""Resolve a typed, intensity-graded event to an actual sound file.

``docs/sfx-design.md`` lists "the sounds are macOS system sounds" as problem #1:
they do not exist off a Mac, they sound like a Mac, and their licence is not
ours to publish under. This module is the indirection that fixes it — an event
names a *role*, not a file, and the role is resolved in three steps:

1. **A file we shipped** — ``assets/audio/sfx/<role>/*.wav`` if any are present.
   Cheapest, most predictable, and what a production library slots into.
2. **Generated by ComfyUI** — ElevenLabs text-to-sound-effects, keyed by prompt
   so the same sound is only ever paid for once. This is alternative "D" in
   ``docs/sfx-design.md`` §4, made concrete.
3. **A macOS system sound** — the old behaviour, demoted to last resort.

Generated files are cached under ``assets/audio/sfx/generated/`` and are
gitignored: they cost money to make but are reproducible from the catalog, and
generated audio is not ours to redistribute.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from pipeline import comfyui
from pipeline.sfx_events import DEFAULT_TYPE, EVENT_TYPES

SFX_ROOT = Path("assets/audio/sfx")
GENERATED_DIR = SFX_ROOT / "generated"
INDEX_PATH = GENERATED_DIR / "index.json"

SFX_WORKFLOW = "07_sfx/elevenlabs_text_to_sound_effects.json"
MUSIC_WORKFLOW = "07_sfx/sonilo_text_to_music.json"

AUDIO_SUFFIXES = (".wav", ".mp3", ".aiff", ".flac", ".ogg", ".m4a")

# An event's intensity picks which variant of a role is used. Three steps is
# enough to hear a difference without tripling what a concept costs to voice.
BUCKETS = ("soft", "mid", "hard")
SOFT_MAX = 0.34
MID_MAX = 0.67

DEFAULT_DURATION = 1.2
DEFAULT_PROMPT_INFLUENCE = 0.45


def bucket_for(intensity: float) -> str:
    """Which variant of a role an intensity asks for."""
    try:
        value = float(intensity)
    except (TypeError, ValueError):
        value = 0.6
    if value < SOFT_MAX:
        return "soft"
    if value < MID_MAX:
        return "mid"
    return "hard"


def event_spec(catalog: dict, event_type: str, intensity: float) -> dict | None:
    """The generation spec for one event type at one intensity.

    Accepts either shape in ``catalog.yaml``::

        impact:   {soft: {...}, mid: {...}, hard: {...}}   # graded
        collapse: {prompt: "...", duration: 2.0}           # one sound for all

    Returns None when the type is not in the catalog at all, which is the signal
    to fall back to a system sound.
    """
    events = (catalog or {}).get("sfx_events") or {}
    # An unknown type resolves to the default entry, and takes its name with it:
    # keying the cache on the requested name would save the same audio again
    # under every typo that ever reached here.
    resolved = event_type if event_type in events else DEFAULT_TYPE
    entry = events.get(resolved)
    if not isinstance(entry, dict):
        return None

    bucket = bucket_for(intensity)
    graded = entry.get(bucket)
    if isinstance(graded, dict):
        spec = {**{k: v for k, v in entry.items() if k not in BUCKETS}, **graded}
    elif "prompt" in entry:
        spec = dict(entry)
        bucket = "all"
    else:
        return None

    if not spec.get("prompt"):
        return None
    spec.setdefault("duration", DEFAULT_DURATION)
    spec.setdefault("prompt_influence", DEFAULT_PROMPT_INFLUENCE)
    spec.setdefault("loop", False)
    spec.setdefault("variants", 1)
    spec["bucket"] = bucket
    spec["type"] = resolved
    return spec


def cache_key(spec: dict, variant: int = 0) -> str:
    """Stable id for one generated sound.

    Keyed on everything that changes the audio, so editing a prompt yields a new
    file instead of silently reusing the old one — and so a re-run of the same
    concept costs nothing.
    """
    payload = json.dumps(
        {
            "prompt": spec["prompt"],
            "duration": round(float(spec["duration"]), 3),
            "prompt_influence": round(float(spec["prompt_influence"]), 3),
            "loop": bool(spec["loop"]),
            "variant": int(variant),
        },
        sort_keys=True, ensure_ascii=False,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def cached_path(spec: dict, variant: int = 0) -> Path:
    """Where a generated sound lives, whether or not it exists yet."""
    return GENERATED_DIR / f"{spec['type']}_{spec['bucket']}_{cache_key(spec, variant)}.mp3"


def library_sounds(role: str) -> list[Path]:
    """Sounds we shipped for a role, if any. Sorted so round-robin is stable."""
    directory = SFX_ROOT / role
    if not directory.is_dir():
        return []
    return sorted(p for p in directory.iterdir() if p.suffix.lower() in AUDIO_SUFFIXES)


def _record_index(spec: dict, variant: int, path: Path, stub: bool = False) -> None:
    """Note what each cached file was made from, so the cache is inspectable.

    Stub tones are recorded too, and marked: a cache full of placeholders looks
    identical to a cache full of real sounds until you read this.
    """
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    try:
        index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        index = {}
    index[path.name] = {
        "type": spec["type"], "bucket": spec["bucket"], "variant": variant,
        "prompt": spec["prompt"], "duration": spec["duration"], "stub": stub,
    }
    INDEX_PATH.write_text(json.dumps(index, ensure_ascii=False, indent=2), encoding="utf-8")


def generate(spec: dict, variant: int = 0, dry_run: bool | None = None) -> Path | None:
    """Make one sound (or return the cached one). None if nothing was produced.

    ``dry_run`` returns None without spending anything, which is what makes
    ``sfx-build --dry-run`` able to price a concept before committing to it.
    """
    target = cached_path(spec, variant)
    if target.is_file():
        return target

    dry_run = comfyui.dry_run_mode() if dry_run is None else dry_run
    if dry_run:
        return None

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    if not comfyui.comfyui_available():
        # Not a real sound, but a *timed* one: the mix, and the timing report
        # that reads it back, stay exercisable with only ffmpeg installed.
        freq = {"soft": 880, "mid": 520, "hard": 240}.get(spec["bucket"], 440)
        comfyui.stub_tone(target, min(1.5, float(spec["duration"])), freq=freq)
        _record_index(spec, variant, target, stub=True)
        return target

    from simulators.comfyui import resolve_overrides
    files = comfyui.run_workflow(
        SFX_WORKFLOW,
        resolve_overrides(SFX_WORKFLOW, {
            "prompt": spec["prompt"],
            "duration": float(spec["duration"]),
            "loop": bool(spec["loop"]),
            "prompt_influence": float(spec["prompt_influence"]),
            "prefix": f"sfx/{spec['type']}_{spec['bucket']}",
        }),
        GENERATED_DIR,
    )
    produced = next((p for p in files if p.suffix.lower() in AUDIO_SUFFIXES), None)
    if produced is None:
        return None
    if produced != target:
        produced.replace(target)
    _record_index(spec, variant, target)
    return target


def resolve_event_sound(catalog: dict, event_type: str, intensity: float,
                        occurrence: int = 0, generate_missing: bool = False,
                        dry_run: bool | None = None) -> tuple[Path | None, str]:
    """Pick the file for one event. Returns ``(path, origin)``.

    ``origin`` is one of ``library`` / ``generated`` / ``none`` and is what the
    SFX report counts — knowing *how* a sound was found is the difference
    between "this concept is voiced" and "this concept fell back to beeps".

    ``occurrence`` round-robins across whatever variants exist so a chain of
    identical impacts does not fire the identical file every time.
    """
    role = event_type if event_type in EVENT_TYPES else DEFAULT_TYPE

    shipped = library_sounds(role)
    if shipped:
        return shipped[occurrence % len(shipped)], "library"

    spec = event_spec(catalog, role, intensity)
    if spec is None:
        return None, "none"

    variants = max(1, int(spec.get("variants") or 1))
    variant = occurrence % variants
    target = cached_path(spec, variant)
    if target.is_file():
        return target, "generated"
    if generate_missing:
        made = generate(spec, variant, dry_run=dry_run)
        if made is not None:
            return made, "generated"
    return None, "none"


def required_sounds(catalog: dict, events: list[dict]) -> list[dict]:
    """Every distinct sound a set of events needs, with its cache state.

    Distinct means "one file": two events in the same type/bucket/variant share
    a sound and are paid for once. This is what ``sfx-build`` iterates over, and
    why a 40-impact chain does not mean 40 API calls.
    """
    seen: dict[Path, dict] = {}
    counts: dict[str, int] = {}
    for event in events:
        role = event.get("type") or DEFAULT_TYPE
        spec = event_spec(catalog, role, event.get("intensity", 0.6))
        if spec is None:
            continue
        occurrence = counts.get(f"{role}:{spec['bucket']}", 0)
        counts[f"{role}:{spec['bucket']}"] = occurrence + 1
        variant = occurrence % max(1, int(spec.get("variants") or 1))
        path = cached_path(spec, variant)
        if path in seen:
            seen[path]["events"] += 1
            continue
        seen[path] = {
            "path": path, "spec": spec, "variant": variant,
            "cached": path.is_file(), "events": 1,
        }
    return sorted(seen.values(), key=lambda s: (s["spec"]["type"], s["spec"]["bucket"]))


def music_path(prompt: str, duration: int, name: str) -> Path:
    """Where a generated BGM bed lives, keyed like the one-shots."""
    key = hashlib.sha256(
        json.dumps({"prompt": prompt, "duration": int(duration)},
                   sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()[:16]
    return GENERATED_DIR / f"bgm_{name}_{key}.mp3"


def generate_music(prompt: str, duration: int, name: str = "ambient",
                   generate_missing: bool = False,
                   dry_run: bool | None = None) -> Path | None:
    """Generate (or reuse) a background music bed. None if nothing was produced.

    Longer than the video on purpose: the compositor loops and trims the bed, and
    a loop point landing inside the piece is more noticeable than a fade.
    """
    duration = max(10, int(duration))
    target = music_path(prompt, duration, name)
    if target.is_file():
        return target
    if not generate_missing:
        return None

    dry_run = comfyui.dry_run_mode() if dry_run is None else dry_run
    if dry_run:
        return None

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    if not comfyui.comfyui_available():
        return None  # a stub drone would only add noise under the effects

    from simulators.comfyui import resolve_overrides
    files = comfyui.run_workflow(
        MUSIC_WORKFLOW,
        resolve_overrides(MUSIC_WORKFLOW, {
            "prompt": prompt, "duration": duration, "seed": 0,
            "prefix": f"bgm/{name}",
        }),
        GENERATED_DIR,
    )
    produced = next((p for p in files if p.suffix.lower() in AUDIO_SUFFIXES), None)
    if produced is None:
        return None
    if produced != target:
        produced.replace(target)
    return target


# ComfyUI's published rate for ElevenLabs text-to-sound-effects. Used only to
# print an estimate before spending; the real charge is on platform.comfy.org.
ELEVENLABS_USD_PER_MINUTE = 0.14
