AVAILABLE_SCENES = [
    "double_pendulum",
    "fluid_ink",
    "sand_collapse",
    "lorenz_attractor",
    "domino_chain",
    "paper_to_cloth",
    "cloth_drop_faces",
    "magnetic_pendulum",
    "ring_escape",
    "marble_race",
    "press_crush",
    "glass_fracture_wall",
    "soft_body_torus_compare",
    "growing_ball",
    "pyramid_collapse",
    "funnel_vortex",
]
